apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-python
spec:
  template:
    spec:
      containers:
        - name: alpine-python
          resources:
            limits:
              cpu: 0.5
              memory: 4Gi
            requests:
              cpu: 0.1
              memory: 64Mi