apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-python
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      micro-svc: alpine-python
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    spec:
      containers:
        - name: alpine-python
          image: alpine-python
          command: ["sh", "-c", "tail -f /dev/null"]
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      terminationGracePeriodSeconds: 15
