apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpine-python

resources:
  - ../../base/

patchesStrategicMerge:
  - patches/alpine-python.yaml

images:
- name: alpine-python
  newName: bentomcfeeley/alpine-python
  newTag: "stage"