name: Publish Docker Image

on:
  push:
    branches: [ "main" ]

env:
  CURR_DATE==$(date +%s)

jobs:

  build-and-tag:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v4
    - name: Build and Push image to DockerHub
      run: |
        docker build . --file Dockerfile --tag bentomcfeeley/alpine-python:$CURR_DATE
        docker push bentomcfeeley/alpine-python:$CURR_DATE

    - uses: actions/checkout@v4
    - name: Vulnerability Summary
      run: |
        docker scout cves bentomcfeeley/alpine-python:$CURR_DATE

    - uses: actions/checkout@v4
    - name: Vulnerability Reccomendations
      run: |
          docker scout reccomendations bentomcfeeley/alpine-python:$CURR_DATE