name: Build image and scan

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-tag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        currDate=$(date +%s)
        docker build . --file Dockerfile --tag bentomcfeeley/alpine-linux:$currDate
        docker push bentomcfeeley/alpine-linux:$currDate
